services:
  wwi-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    container_name: wwi-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "IntelliSales!2026"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ./data/raw:/var/opt/mssql/backup
